server:
  port: 8085

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Add these for better debugging
        generate_statistics: true
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ZXhhbXBsZS1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LTI1Ni1iaXQ=
  expiration: 86400000
  refresh-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.org.crm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.orm.jpa: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 