services:
  - type: web
    name: crm-customer-service
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: mvn spring-boot:run
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        value: crm_user
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://crm-discovery-service.onrender.com/eureka/
      - key: REDIS_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false 