services:
  - type: web
    name: crm-notification-service
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: mvn spring-boot:run
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        value: crm_user
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://crm-discovery-service.onrender.com/eureka/
      # Redis configuration removed for deployment without notification service
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: 587
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: true
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: true 