services:
  - type: web
    name: crm-auth-service
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: mvn spring-boot:run
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        value: crm_user
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        value: crmAuthSecretKeyForJWTTokenGeneration2024
      - key: JWT_EXPIRATION
        value: 86400000
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://crm-discovery-service.onrender.com/eureka/
      # Redis configuration removed for deployment without notification service 